### ISSUE TITLE
Limit file size for uploaded images

### ISSUE THREAD

**Issue by klappradla** [imGraetzl/im_graetzl#196] opened 2016-02-17 15:05 UTC
Limit file-size for uploaded images: e.g. 5MB _(decent value still to be found)_
- [ ] Limit on Refile backend: https://github.com/refile/refile/issues/314
- [ ] Validate size: https://github.com/refile/refile/issues/387

**Comment by anchal0997** [comment] 2018-02-26 14:23
Hi @klappradla ,
I am new to this organisation and I am aspiring for RGSoC. I would like to work on this issue, if mentored.

**Comment by klappradla** [comment] 2018-02-26 18:52
Hi @anchal0997 👋 

I'm afraid I cannot be of much help here 😞  I'm actually no longer involved in this project and therefore can't even tell whether this issue is still relevant... 🙈 

@malano or @metakermit would be the people with insight on this 🤓 As far as I remember, the project's issue tracker isn't even on Github any more.

Aside that, all the best for you RGSoC application 💚

**Comment by metakermit** [comment] 2018-02-27 10:07
Hi @anchal0997! Welcome and glad you're interested in helping out 🙂 

Yes, as @klappradla says we mostly use Basecamp for issue tracking these days. But I was actually talking to @malano that for the purposes of RGSoC we might switch over to GitHub issues for these types of technical issues and features we mark as suitable for newcomers, so that everything happens in the open.

That said, this issue is still open as far as I know :) What do you say @malano? Would this perhaps be a nice first task for @anchal0997? Can you maybe write a use case of how to reproduce the current behaviour and what do we want to happen instead?

**Comment by malano** [comment] 2018-02-27 22:33
Hi @anchal0997 

Thanks for your help regarding this!
And yes, as @metakermit said we have not used the Issues Tab on Github for managing Features, Bugs and so on in the past - but in the future we want to switch from Basecamp to Github so that its easier and public.

So for sure we can have a look at this, but i think its not such a major problem - or its possible to have a look @metakermit regarding the files sizes of the images which are uploaded  - so if we have an larger number of big images?!

but I take your first request for the occasion to bring life into the issues tab - I believe in basecamp are some recent tasks that could be exciting. I will make this the next days

and hey @klappradla - hope you are doing well!

cheers and thanks
michael

**Comment by anchal0997** [comment] 2018-02-28 06:59
Hi @malano 
I would love to work on the issues and would like to add some more features to the project. 
Is there any slack channel where we can discuss issues and stuff? 

Regards 
Anchal

**Comment by suleka96** [comment] 2018-03-07 09:24
Hi
my team mate and I also applied for RGSoC. If the issue is not fixed yet, I would also like to work on this issue.

**Comment by metakermit** [comment] 2018-03-07 11:04
Hi Suleka,

welcome and glad to hear you're interested. I just talked to @malano today
and we said we will add some more issues to GitHub – there should be plenty
of things to do.

Maybe for starters both you and @anchal0997 can try setting up the local
dev environment by following the README instructions – if there are any
problems feel free to open a new issue and we'll try to help you out.

In the mean time, we'll try to structure the tasks a bit. BTW, do you know
when would you start working on the tasks at hand? We have to wait for some
official start of RGSoC or are you interested to already do some light
contributions before the summer?

Cheers,
Dražen

**Comment by anchal0997** [comment] 2018-03-11 09:29
Hey @metakermit ,

My partner and I would like to make contributions to the project. I have tried setting up the environment but I am facing some problem while installing the bundle but I am trying to fix the problem. If the problem won't be fixed in 24hrs then I will take your advice. Kindly tell me from where should I start contributing?

Regards,
Anchal

**Comment by malano** [comment] 2018-03-12 11:29
Hi @anchal0997 

How is it going on regarding the local setup and bringing the app running on your localhost ... ?!
I think its good to start first with really small things, just to understand the app and dependencies and understand how everything works together. May a really small first thing could be this issue:
https://github.com/imGraetzl/im_graetzl/issues/224

I'm also looking for new small more exciting features ... (write you soon). But for starting i think this small bugfix could be good?! what do you think?

cheers
michael

**Comment by metakermit** [comment] 2018-03-12 11:30
Hey @anchal0997 ok, feel free to open a new issue if you don't manage to fix the bundling error. We're pretty much all using macOS, I think, so it's very likely that the instructions will have to be updated to work on other OS-es (PRs welcome if you figure out how to fix something on your own :) )

Regarding good first problems to tackle, we've opened a few issues marked [good first issue](https://github.com/imGraetzl/im_graetzl/labels/good%20first%20issue):

- https://github.com/imGraetzl/im_graetzl/issues/224
- https://github.com/imGraetzl/im_graetzl/issues/226

**Closed** 2024-05-01 13:05 UTC
Labels: bug
